version: "0.1"
metadata:
  name: lenet
data:
  src: Fashion-MNIST
layers:
  - type: conv
    kernel_size: 5
    padding: 2
    size: 6x28x28
  - type: sigmoid
  - type: pool
    kernel_size: 2
    size: 6x14x14

  - type: conv
    kernel_size: 5
    size: 16x10x10
  - type: sigmoid
  - type: pool
    kernel_size: 2
    size: 16x5x5

  - type: dense
    size: 120
  - type: sigmoid

  - type: dense
    size: 84
  - type: sigmoid

  - type: dense
    size: 10
  - type: softmax
training:
  device: cuda
  optimizer:
    type: adam
  loss:
    type: cross_entropy
  epochs: 20
  batch_size: 64
