version: "0.1"
metadata:
  name: linear
data:
  src: Fashion-MNIST
layers:
  - type: dense
    size: 10
  - type: softmax
training:
  device: cuda
  optimizer:
    type: adam
  loss:
    type: cross_entropy
  epochs: 20
  batch_size: 64
